config/routes.rb
Rails.application.routes.draw do
  resources :boards
    resources :statuses 
      resources :cards
    

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
     has_many :statuses
     has_many :cards
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :board
    has_one :status
    validates :description, presence: true,
                    length: { minimum: 8 }
end

app/models/status.rb
class Status < ApplicationRecord
    belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
        @boards = Board.all
    end

    def show
        @board = Board.find(params[:id])
    end

    def new 
        @board= Board.new
    end 

    def edit 
        @board = Board.find(params[:id])
    end 

    def create
        @board = Board.new(board_params)
 
        if @board.save
            redirect_to @board
        else 
            render 'new'
        end 
    end

    def update
        @board = Board.find(params[:id])
 
        if @board.update(board_params)
            redirect_to @board
        else
            render 'edit'
        end
    end

    private
    def board_params
        params.require(:board).permit(:title, :description)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

    def index
        @cards = Card.all
    end

    def show
        @card = Card.find(params[:id])
    end

    def new 
        @card = Card.new
    end 

    def edit 
        @board = Board.find(params[:board_id])
        @status = Status.find(params[:status_id])
        @card = Card.find(params[:id])
    end 

    def create
        @board = Board.find(params[:board_id])
        @status = Status.find(params[:status_id])
        @card = Card.new(card_params)
 
        if @card.save
            redirect_to @card
        else 
            render 'new'
        end 
    end

    def update
        @board = Board.find(params[:board_id])
        @status = Status.find(params[:status_id])
        @card = Card.find(params[:id])
 
        if @card.update(card_params)
            redirect_to @card
        else
            render 'edit'
        end
    end

    private
    def card_params
        params.require(:card).permit(:description)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

      def index
        @statuses = Status.all
    end

    def show
        @status = Status.find(params[:id])
    end

    def new 
        @status = Status.new
    end 

    def edit 
        @board = Board.find(params[:board_id])
        @status = Status.find(params[:id])
    end 

    def create
        @board = Board.find(params[:board_id])
        @status = Status.new(status_params)
 
        if @status.save
            redirect_to @status
        else 
            render 'new'
        end 
    end

    def update
        @board = Board.find(params[:board_id])
        @status = Status.find(params[:id])
 
        if @status.update(status_params)
            redirect_to @status
        else
            render 'edit'
        end
    end

    private
    def status_params
        params.require(:status).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boards/edit.html.erb
<h1>Edit Board</h1>

<%= form_for :board, url: board_path(@board), method: :patch do |f| %>
 
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@board.errors.count, "error") %> prohibited
        this board from being saved:
      </h2>
      <ul>
        <% @board.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_area :title %>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<div class = "header"> 
<img src="../assets/images/header-logo-2x.png" alt="Logo">
</a>
</div>
 <tr><td><%= link_to 'New Board', new_board_path %></td><tr>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
 
  <% @boards.each do |board| %>
    <tr>
      <td><%= board.title %></td>
      <td><%= board.description %></td>
      <td><%= link_to 'Show', board_path(board) %></td>
      <td><%= link_to 'Edit', edit_board_path(board) %></td>
    </tr>
  <% end %>
</table>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= form_for :board, url: boards_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/boards/show.html.erb
<h2> Board</h2>
<p>
  <strong>Title:</strong>
  <%= @board.title %>
  <strong>Description:</strong>
  <%= @board.description %>
</p>

<h2>Statuses</h2>
<%= render @board.statuses %>
 
<h2>Add a Status:</h2>
<%= form_for([@board, @board.status.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p> 
<% end %>

<%= link_to 'Back', boards_path %>

app/views/cards/edit.html.erb
<h1>Edit Card</h1>

<%= form_for :card, url: card_path(@card), method: :patch do |f| %>
 
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<div class = "header"> 
<img src="../assets/images/header-logo-2x.png" alt="Logo">
</a>
</div>
 <tr><td><%= link_to 'New Card', new_card_path %></td><tr>
<table>
  <tr>
    <th>Description</th>
  </tr>
 
  <% @cards.each do |card| %>
    <tr>
      <td><%= card.description %></td>
      <td><%= link_to 'Show', card_path(card) %></td>
      <td><%= link_to 'Edit', edit_card_path(card) %></td>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= form_for :card, url:cards_path do |f| %>

 <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<h2> Cards </h2>
<p>
  <strong>Description:</strong>
  <%= @card.description %>
</p>

<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trelloapplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statuses/_status.html.erb
<p>
  <strong>Title:</strong>
  <%= status.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= status.description %>
</p>

app/views/statuses/edit.html.erb
<h1>Edit Status</h1>

<%= form_for :status, url: status_path(@status), method: :patch do |f| %>
 
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@status.errors.count, "error") %> prohibited
        this status from being saved:
      </h2>
      <ul>
        <% @status.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_area :title %>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', boards_path %>

app/views/statuses/index.html.erb
<div class = "header"> 
<img src="../assets/images/header-logo-2x.png" alt="Logo">
</a>
</div>
 <tr><td><%= link_to 'New Status', new_status_path %></td><tr>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
 
  <% @statuses.each do |status| %>
    <tr>
      <td><%= status.title %></td>
      <td><%= status.description %></td>
      <td><%= link_to 'Show', status_path(status) %></td>
      <td><%= link_to 'Edit', edit_status_path(status) %></td>
    </tr>
  <% end %>
</table>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= form_for :status, url:status_path do |f| %>

 <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@status.errors.count, "error") %> prohibited
        this status from being saved:
      </h2>
      <ul>
        <% @status.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_area :title %>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<h2> Statuses</h2>
<p>
  <strong>Description:</strong>
  <%= @status.title %>
  <strong>Description:</strong>
  <%= @status.description %>
</p>

<%= link_to 'Back', statuses_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<%= link_to 'Cards', controller: 'cards' %>


<%= link_to 'New Card', new_card_path %>